safe-global/safe-gateway-typescript-sdk

src/endpoint.ts, src/index.ts, src/types/gateway.ts, src/types/transactions.ts, src/utils.ts, tests/endpoint.test.js, tests/utils.test.js
Adding an endpoint to create Safe transactions – `transactions/{safe_address}/propose`.
We've been only doing GET requests so far, so some changes to support POST requests were needed.
=> Add "/transactions/{safe_address}/propose" and allow POST requests

package.json, src/index.ts
Because transaction types were not imported from index, we had to copy them to src/types in safe-react and if we tried to do `import { Operation, TransactionStatus } from '@gnosis.pm/safe-react-gateway-sdk/dist/types/transactions'` webpack was not happy with it for some reason.
This way it works perfectly, tested it on my local machine
=> Feature: export transaction types from index

.github/workflows/lint.yml, .github/workflows/test.yml, .gitignore, package.json, src/endpoint.ts, src/index.ts, src/utils.ts, tests/endpoint.test.js, tests/utils.test.js
As it turned out in https://github.com/gnosis/safe-react/pull/2615, when the gateway responds to the `/propose` request, the response is empty and thus cannot be parsed as JSON.
This PR adds a fallback to the response text.
=> Fallback to a text response if JSON fails

package.json, src/types/transactions.ts
There was a typo in one of SafeAppInfo types. We are going to unify the used type and ensure we are using the correct one
For instance `logoUrl` should be `logoUri` as correctly defined by the type that we already have for SafeAppInfo
=> Fix typo in SafeAppInfo type

package.json, src/types/transactions.ts
The transaction reducer required casting due to this missing `type` key. By adding it, it allows the removal of the casting.
=> Add missing `type`s to `TransactionListItem`

package.json, src/types/chains.ts
The `/chains` returned `safeAppsRpcUri` type has been added to the `ChainInfo` type.
=> Add safeAppsRpcUri type

src/types/chains.ts
It wasn't used by safe-react and thus deleted.
=> Chore: rm unused ERC1155 feature flag

.github/workflows/release.yml
Automatically publishing an NPM package w/o 2FA poses a security risk, so we're disabling this.
cc @rmeissner
=> Chore: remove automated npm publishing

e2e/get-chains-config.test.ts, e2e/get-owned-safes.test.ts, e2e/get-safe-apps.test.ts, e2e/post-safe-gas-estimation.test.ts, e2e/propose-transaction.test.ts, package.json, src/index.ts, src/types/api.ts, src/types/safe-apps.ts
Currently the web app is using the config service directly to fetch the Safe Apps list.
This PR adds the Safe Apps List endpoint to the React Gateway SDK.
Ticket: https://github.com/gnosis/safe-react-gateway-sdk/issues/21
Added minor fixes in other unrelated e2e tests.
=> Added Safe Apps List endpoint

src/endpoint.ts, src/index.ts, src/types/api.ts, src/types/decoded-data.ts, src/utils.ts, tests/endpoint.test.js, tests/utils.test.js
The previous removal off `paths`/`operations` typing reverts the practice of following OpenAPI. All tests, utils, etc. now follow it again.
=> Revert types to follow that of OpenAPI

package.json, src/index.ts, src/types/master-copies.ts
New types were included in the SDK but not exported.
=> Export master copy/decoded data types

e2e/post-safe-gas-estimation.test.ts, package.json, src/index.ts, src/types/api.ts, src/types/transactions.ts
A separate v2 version for Safe transaction estimation was added yesterday, along with related types. As this is only being used in one place in `safe-react`, v1 is no longer needed and, as such, is removed and v2 used in place.
=> Remove Safe transaction estimation versioning

.github/workflows/typedoc.yml, README.md, e2e/propose-transaction.test.ts, package.json, src/index.ts, src/types/api.ts, tests/endpoint.test.ts, tests/types.test.ts, tests/utils.test.ts, yarn.lock
Resolves #46 and #8
* I've converted the unit tests to TypeScript
* Added a test that simply imports a few random types from the package index
* I've also unified the endpoints to not have a trailing slash
=> Chore: TypeScript in tests

package.json, src/types/api.ts
The client gateway uses a snake case and not a camel case and I messed it up. Sorry
=> Fix `client_url` param casing

package.json, src/types/safe-apps.ts
Ticket: https://github.com/gnosis/safe-react-apps/issues/286
With the current SafeAppsResponse type we only accept arrays with 1 item:
Changed
```
export type SafeAppsResponse = [SafeAppData]
```
Into
```
export type SafeAppsResponse = SafeAppData[]
```
=> Fixed SafeAppsResponse types to avoid only 1 item array

package.json, src/types/transactions.ts
In accordance with the new `trustedDelegateCallTarget` flag [added to the transaction data](https://github.com/gnosis/safe-client-gateway/issues/725), this has been added to the `TransactionData` type.
=> chore: add `trustedDelegateCallTarget` transaction flag

package.json, src/types/transactions.ts
In fixing an isse with button text (https://github.com/gnosis/safe-react/issues/3352), it became apparent that the `PENDING_FAILED` (frontend-only) status was redundant and had been included in the Safe as a placeholder. This PR removes it to keep it inline with the frontend.
=> fix: remove redundant status

package.json, src/types/transactions.ts
While adding the `safe-react-gateway-sdk` to the `safe-apps-sdk` to align in types I detected that this prop was missing and it's returned in the balances endpoint
=> Add type property to TokenInfo

package.json, webpack.config.js
Resolves https://github.com/gnosis/safe-apps-sdk/issues/292
We are adding `globalThis` prop to the webpack config as the default `self`  in the compiled files is causing problems with SSR solutions as NextJS
=> feat: Use globalThis

package.json, src/types/common.ts, src/types/transactions.ts
The client gateway returns NATIVE_TOKEN for TokenType enum and Transaction type uses NATIVE_COIN to define native chain token.
We should separate and not use the same TokenType to define both properties.
Also I made the transaction file to depend on the common that makes more sense
Resolves https://github.com/gnosis/safe-react-apps/issues/355
=> fix: TokenType for balances 

e2e/safe-collectibles-list.test.ts, package.json, src/types/transactions.ts
Label is specified to be either "Queued" or "Next" as an enum.
=> Fix: enum for tx Label values

package.json, src/types/safe-apps.ts
Add the `tags` property to
`https://gnosis.github.io/safe-client-gateway/docs/routes/safe_apps/routes/fn.get_safe_apps.html`
response given https://github.com/gnosis/safe-config-service/pull/496
=> feat: add tags to SafeAppData

README.md, e2e/get-chains-config.test.ts, e2e/get-decoded-data.test.ts, e2e/get-master-copy.test.ts, e2e/get-owned-safes.test.ts, e2e/get-safe-apps.test.ts, e2e/post-safe-gas-estimation.test.ts, e2e/propose-transaction.test.ts, e2e/safe-collectibles-list.test.ts, e2e/safes-read.test.ts, package.json, src/config.ts, src/index.ts
Allow the user to override the base URL of the CGW for all endpoints at once. Instead of passing it into every endpoint function.
This makes the SDK stateful, which is undesired, but at the same time easier to use, which is good.
Up for discussion.
=> Breaking: set the base URL for entire API

package.json, src/types/transactions.ts
Exports the enum `SettingsInfoType`
=> refactor: add SettingsInfo type

package.json, src/index.ts, src/types/api.ts, src/types/chains.ts, src/types/common.ts, src/types/transactions.ts
This adds new functions/types to call the new, filterable endpoints for incoming, module and multisig transactions.
=> feat: add tx filter endpoints

README.md
The links in the README.md were still pointing to the old gnosis.pm github pages which don't exist anymore.
=> fix: links to docs in README.md

package.json, src/types/common.ts
Changes the SafeInfo's `guard` field to be nullable.
This line converts the 0 address which is in the safe-contract to `null`:
https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/safes/converters.rs#L53
Also here is an example Safe response without an transaction guard defined:
```
{
"address": {
"value": "0x180E0F9729EB4DD2d740052CB314dC918Ac0570B"
},
"chainId": "4",
"nonce": 5,
"threshold": 1,
"owners": [
{
"value": "0x3819b800c67Be64029C1393c8b2e0d0d627dADE2"
}
],
"implementation": {
"value": "0xd9Db270c1B5E3Bd161E8c8503c55cEABeE709552"
},
"modules": [
{
"value": "0xCFbFaC74C26F8647cBDb8c5caf80BB5b32E43134"
},
{
"value": "0xaDa0e6Fe72A212240A4b5e7A867c6686e8aF0956"
},
{
"value": "0x4753E44EE22b5a4c9D16877e104D761bB83937A1"
}
],
"fallbackHandler": {
"value": …
```
=> fix: SafeInfo guard can be null

scripts/make-cgw-types.sh
A script that generates TypeScript types from the CGW Swagger.
Unfortunately, CGW only exposes request types, not the responses. Still useful to type the endpoints.
=> Chore: add a script to export OpenAPI types from the CGW Swagger

e2e/propose-transaction.test.ts, e2e/safe-collectibles-list.test.ts, package.json, src/types/common.ts, src/types/transactions.ts
Resolves #30.
All of the transaction models are using the `Option` generic, which returns undefined, not null.
Also fixed the `modules` type in SafeInfo. It does come as `null` when no modules are added.
=> Fix: null -> undefined in Transaction types

package.json, src/types/common.ts, src/types/decoded-data.ts
`TokenInfo` isn't documented, but in the code its `logoUri` isn't optional.
=> Fix: logoUri is not optional in TokenInfo

README.md, e2e/safes-read.test.ts, package.json, src/index.ts, src/types/common.ts, src/types/safe-info.ts
This is needed to avoid comparing the version of the Safe on the client side.
=> Fix: add implementationVersionState to SafeInfo

package.json, src/types/api.ts
Looks like we were lacking type checking in the required checks. I've added tsc to the lint command.
=> Fix: SafeInfo import

.prettierignore, e2e/safe-collectibles-list.test.ts, package.json, src/index.ts, src/types/api.ts, src/types/chains.ts, src/types/common.ts, src/types/transactions.ts
A new endpoint for paginated NFTs.
=> Feat: add collectibles v2

package.json, src/types/transactions.ts
These statuses were never returned from the CGW and were client-side only. There's no need for them anymore.
=> Fix: remove deprecated client-side tx statuses

src/types/transactions.ts
A tiny refactoring: Transfer and Custom were the only two types defined as interfaces accidentally.
=> Refactor: interface -> type

package.json, src/types/api.ts
We've added support for the `url` query param to the `safe-apps` endpoint to fetch a single app by URL in https://github.com/safe-global/safe-client-gateway/pull/959, and it's already available on staging https://safe-client.staging.gnosisdev.com/index.html. Production will be released the following Monday.
This PR adds types for the query param.
=> Add `url` query param to safe-apps endpoint

package.json, src/types/transactions.ts
Export some missing enum types to be used in the frontend clients:
- [TransactionInfoType](https://safe.global/safe-client-gateway/docs/routes/transactions/models/enum.TransactionInfo.html)
- [ConflictType](https://safe.global/safe-client-gateway/docs/routes/transactions/models/summary/enum.ConflictType.html)
- [TransactionListItemType](https://safe.global/safe-client-gateway/docs/routes/transactions/models/summary/enum.TransactionListItem.html)
=> add missing enum types

package.json, tsconfig.json
#96 didn't work with web-core, it wants CommonJS modules.
I've tested it by copying the dist folder to web-core's node_modules.
=> Chore: use CommonJS modules for dist

package.json, src/types/transactions.ts
Corrects the types for [the forthcoming `trusted` flag](https://github.com/safe-global/safe-client-gateway/issues/1005).
The `boolean` `MultisigExecutionDetails['trusted']` flag has been added.
=> fix: add `trusted` to `MultisigExecutionDetails`

package.json, src/index.ts, src/types/api.ts, src/types/safe-messages.ts
This integrates the endpoints to get all, propose or confirm `SafeMessage`s.
The endpoints and types are implemented according to the [backend spec](https://www.notion.so/EIP-1271-backend-specifications-c0c6ef187425475288216021a7521c82?d=3345071f763246439acfe3c765645369#ad5426ada7c54158b8b04b9a4ca25bac).
=> feat: EIP-1271 propose, confirm and list endpoints

package.json, src/endpoint.ts, src/index.ts, src/types/api.ts, tests/endpoint.test.ts
We can now clearly differentiate GET and POST endpoints by passing or not passing a `body` param.
=> Refactor: allow both get and post methods on the same endpoint

package.json, src/endpoint.ts, src/index.ts, src/types/api.ts, tests/endpoint.test.ts
getEndpoint and postEndpoint for a clear separation of REST methods.
=> Refactor: allow both get and post methods on the same endpoint #101

package.json, src/index.ts, src/types/api.ts, src/types/safe-info.ts, src/types/safe-messages.ts
1. Marks `safeAppId` as optional (which matches that of the transaction service and the gateway [here](https://github.com/safe-global/safe-client-gateway/pull/1020)). No `safeAppId` is present when testing adding a custom app.
2. Adds `getSafeMessage` endpoint for retrieving a `SafeMessage` by hash. It does not return a `type` [as seen here](https://github.com/safe-global/safe-client-gateway/pull/1019).
3. Adds `messagesTag` to Safe info endpoint (as seen [here](https://github.com/safe-global/safe-client-gateway/pull/1013)).
=> fix: make `safeAppId` optional, add `messagesTag` + message endpoint

src/utils.ts
Empty respones from thorwing on parse.
When `json()` is called on the `fetch` response, it is caught. It would otherwise throw if there is no response JSON to parse.
The endpoints in question which caused this error are the proposal/confirmation of Safe messages.
=> fix: prevent parsing empty responses from throwing

package.json, src/types/safe-info.ts
https://github.com/safe-global/web-core/issues/1327 partially
When a Safe is created with an unknown base contract, the gateway returns a `null` `version` and an `UNKNOWN` `implementationVersionState`.
This sets `SafeInfo['version']` to `string | null` and the `ImplementationVersionState` has been extended to include the `UNKNOWN` option.
[Here](https://safe-client.staging.5afe.dev/v1/chains/137/safes/0xF3aa45696f8Bc702D41d11b365C067f26f79fcaA) is a reference Safe.
=> fix: adjust types for unsupported base contract

package.json, src/types/safe-info.ts
For Safe's without Fallback Handler the `fallbackHandler` field is `null`.
=> fix: fallback handler type

package.json, src/types/safe-apps.ts
Implements updated types after https://github.com/safe-global/safe-config-service/issues/755
=> Add type for safe app features

.github/workflows/release.yml, package.json
When generating a changelog, it was taking the previous version from the latest publish package on NPM.  
It should take the latest tag instead.
=> Fix: previous version detection in release automation

.github/workflows/release.yml
`set-output` will be deprecated in May this year, so we need to migrate it as per https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
I've copied this portion of the code from [web-core](https://github.com/safe-global/web-core/blob/dev/.github/workflows/tag-release.yml#L24), where it has worked well for a while, so I assume it will work here as well.
=> Chore: replace deprecated set-output in the deploy workflow

package.json, src/types/transactions.ts
Part of https://github.com/safe-global/web-core/issues/1890
In #117, we updated the type for `data` in `DecodedDataResponse` to be nullable but the corresponding type `DataDecoded` still had `data` to be optional which causes a type mismatch.
- Update `data` in `DataDecoded` to be `string | null`
=> fix: Update transaction data property to be nullable

.github/workflows/lint.yml, .github/workflows/test.yml, package.json, src/index.ts, src/types/api.ts, src/types/delegates.ts, yarn.lock
Partially ports #72.
Types and a method to fetch a delegates list.
=> Feat: add getDeletegates

package.json, src/index.ts, src/types/decoded-data.ts
The CGW allows an optional `to` parameter for the `data-decoder` request so we should have it here as well.
=> Add optional to param to getDecodedData

src/types/chains.ts
Enabled a new way of chain config for fixed EIP-1559 gas prices.
Required for https://github.com/safe-global/safe-wallet-web/issues/2222
Using this we can set 0.1 gwei `maxFeePerGas` and 0.0001 gwei `maxPriorityFeePerGas` on Optimism.
=> feat: fixed EIP-1559 gasprice

package.json, src/endpoint.ts, src/index.ts, src/types/api.ts, src/types/notifications.ts, src/utils.ts
This adds the device/Safe notification (un-)registration endpoints as per https://github.com/safe-global/safe-client-gateway-nest/pull/636:
- `/v1/register/notifications`
- `/v1/chains/{chainId}/notifications/devices/{uuid}/safes/{safe_address}`
- `/v1/chains/{chainId}/notifications/devices/{uuid}`
=> feat: add notification (un-)registration endpoints

src/index.ts
This re-exports the notification types for consistency.
=> fix: re-export notification types

src/index.ts
It's typed as optional in the request type but not in the function signature.
(Introduced in #125.)
=> Fix: getDecodedData "to" param should be optional

package.json, src/utils.ts, tests/utils.test.ts, yarn.lock
A native fetch is available in Node 16, so we can ditch cross-fetch.
=> Refactor: use native fetch

src/types/chains.ts, src/types/transactions.ts
Rust docs were removed so these links in comments don't work anymore.
Resolves #133.
=> Chore: rm outdated comments

package.json
In preparation for release, this bumps the version to 3.11.0.
=> chore: bump version to 3.11.0

src/types/human-description.ts, src/types/transactions.ts
- Adds enum for `RichFragmentType`
- Adds types for `RichDecodedInfo`, `RichDecodedInfoFragment`, `RichTokenValueFragment`, `RichTextFragment`, `RichAddressFragment`
=> Feat: Add richDecodedInfo type to txInfo

package.json, src/index.ts, src/types/api.ts
Adds support for the new getRecommendedNonce endpoint (https://github.com/safe-global/safe-client-gateway/issues/681)
`GET /v1/chains/{chainId}/safes/{safe_address}/recommended-nonce`
=> feat: add recommended nonce endpoint

package.json, src/index.ts, src/types/api.ts, src/types/transactions.ts
Fixes the type introduced in #138 from a `number` to `{nonce: number}`
=> fix: recommended nonce response

package.json, src/index.ts, src/types/api.ts, src/types/transactions.ts
Changes the existing function `getRecommendedNonce` to `getNonces` that returns both the current and recommended nonce according to the CGW: https://github.com/safe-global/safe-client-gateway/pull/817
=> fix: Change getRecommendedNonce to getNonces call

package.json, src/index.ts, src/types/api.ts, src/types/transactions.ts
Adds support for changes introduced in [1.18.0](https://github.com/safe-global/safe-client-gateway/releases/tag/v1.18.0)
- Trusted query param for tx history
- Trusted flag for ERC20 Transfer infos
=> feat: trusted history transaction

package.json, src/index.ts, src/types/api.ts
All tx list endpoints now accept a `timezone_offset` query param (in milliseconds).
Breaking change:
* `getTransactionHistory` and `getTransactionQueue` signature change – they now take a query object _before_ the optional `pageUrl` argument.
=> Feat: add timezone_offset to tx list endpoints

src/types/safe-info.ts
This updates the `SafeInfo['collectiblesTag' | 'txQueuedTag' | 'txHistoryTag' | 'messagesTag']` in accordance with https://github.com/safe-global/safe-client-gateway/pull/909, returning `string | null`.
=> Add `null` to `SafeInfo['collectiblesTag' | 'txQueuedTag' | 'txHistoryTag' | 'messagesTag']`

src/index.ts, src/types/api.ts, src/types/common.ts
Add support for a new endpoint `getAllOwnedSafes` https://github.com/safe-global/safe-client-gateway/pull/1097
`GET /v1/owners/{address}/safes`
=> feat: Add getAllOwnedSafes endpoint

src/types/chains.ts
This adds the new `ChainInfo['chainLogoUri']` in accordance with the recent release of the [Config Service](https://github.com/safe-global/safe-config-service/releases/tag/v2.71.0) and [Client Gateway](https://github.com/safe-global/safe-client-gateway/releases/tag/v1.26.0).
=> Add `chainLogoUri` to `ChainInfo`

package.json, src/endpoint.ts, src/index.ts, src/types/api.ts, src/types/emails.ts, src/utils.ts, tests/endpoint.test.ts, tests/utils.test.ts
- register email address for signer
- change email address for signer
- re-send verification code
- verify email address
- Some of the new endpoints require params in header fields. Therefore this PR adds header params to the api operations.
- [Spec](https://www.notion.so/safe-global/Emails-for-Recovery-7ab374774afd4ff9b484ddf9c627720e)
=> feat: register, change and verify email addresses

src/utils.ts, tests/utils.test.ts
A 204 response doesn't contain a body so calling `response.json()` will throw. This is caught locally and we check if there is a `content-length: 0` header to cover the case of a 204 response. If there is no such header we throw again. The issue is that by default, the CGW returns 204 responses without such a header as it is not enforced.
To solve this we are explicitely checking for a 204 status and don't call `response.json()` in that case.
=> fix: Don't throw for 204 responses

src/types/api.ts
This adds the `trusted` query param. to the `incoming-transfers` endpoint in accordance with https://github.com/safe-global/safe-client-gateway/pull/1214.
=> Add `trusted` query param. to `incoming-transfers` endpoint

src/index.ts, src/types/api.ts, src/types/recovery.ts
- Adds a new endpoint for `addRecoveryModule` ([CGW](https://github.com/safe-global/safe-client-gateway/blob/main/src/routes/recovery/recovery.controller.ts#L17))
=> feat: Add register module address endpoint

src/types/transactions.ts
This adds `MultisigExecutionInfo['proposer']` in accordance with https://github.com/safe-global/safe-client-gateway/pull/1217.
=> feat: add `proposer` to `MultisigExecutionInfo`

src/types/transactions.ts
This moves the `proposer` from the `executionInfo` to the `detailedExecutionInfo` of a multisig transaction [in accordance with the Gateway](https://github.com/safe-global/safe-client-gateway/pull/1234).
=> feat: move `proposer` from `MultisigExecutionInfo` to `MultisigExecutionDetails`

src/index.ts, src/types/api.ts
Adds support for unsubscribe and unsubscribe all endpoints as described in the [API Spec](https://www.notion.so/safe-global/As-an-email-owner-I-want-to-be-able-to-unsubscribe-from-email-notifications-since-I-m-no-longer-int-d5f4491226844e3d9a982819b04bd27f).
=> feat: Add unsubscribe endpoints

scripts/make-cgw-types.sh, src/types/transactions.ts
This PR ads a SwapOrder type for decoded cowswap orders.
=> Feat: add swap type

src/index.ts, src/types/api.ts, src/types/common.ts, src/types/safe-info.ts
A new endpoint to get info, balances and pending tx counts for a list of safes.
Endpoint: https://safe-client.staging.5afe.dev/api#/safes/SafesController_getSafeOverview
=> Feat: safe overviews endpoint

src/index.ts, src/types/api.ts, src/types/decoded-data.ts, src/types/transactions.ts, tests/endpoint.test.ts
There is a new endpoint on the gateway for which we need types. It basically "replaces" the "data-decoder" endpoint and ads more info about for example "swaps".
=> feat: add confirmation view endpoint types

src/index.ts, src/types/transactions.ts
The cgw now also returns appFullData and our getConfirmationView response type was wrong.
=> fix: some swap definitions were wrong

package.json, src/index.ts, src/types/api.ts, src/types/contracts.ts
Adds contract info endpoint which fetched contract name, logo and abis.
=> Feat: contract info endpoint

.github/workflows/lint.yml, .github/workflows/release.yml, package.json
* Avoid failing the release action when a new version isn't detected.
* Fix the lint action.
=> Chore: fix lint action + skip release gracefully

src/types/chains.ts
Adds a flag to chainInfo for whether zerion balances are supported on a chain. To be used for ERC20 balances of counterfactual safes.
Reflecting [changes to the CGW](https://github.com/safe-global/safe-client-gateway/pull/1648).
=> Feat: add `balancesProvider` to chainInfo type

src/types/transactions.ts
This PR ads a new TWAP order type. I also refactored the definitions a bit and we now have a discriminated union type Order that we can use when we are fine with either SwapOrder ot TwapOrder.
=> feat: add twap type

.github/workflows/release.yml
With this change bump PRs will be removed form the generated changelog. For this to work the version number needs to be part of the commit title
=> Chore: remove bump PRs from changelog

src/endpoint.ts, src/index.ts, src/types/api.ts, src/types/auth.ts, src/utils.ts, tests/endpoint.test.ts
- Adds two new functions `getAuthNonce` and `verifyAuth`
- Adds `includeCredentials` parameter to get/post/put/delete calls
1. Checkout this branch locally and run `yarn link`
2. Use the local package in https://github.com/safe-global/safe-wallet-web/pull/3853
3. Observe the sign in flow still works
=> feat: Add siwe auth endpoints

src/index.ts, src/types/api.ts, src/types/decoded-data.ts, src/types/transactions.ts
We agreed that the order types should be more generic and decided to drop the CoW from their name.
=> reafactor: order types

src/types/transactions.ts
The send/receive events now have additional data if they are triggered by a cow swap. 
The new type is at the same time a transfer and an order.
=> feat: add new SwapTransferOrder type

src/types/api.ts
Part of https://github.com/safe-global/safe-wallet-web/issues/3815
A new query param to get module txs by hash.
https://safe-client.safe.global/api#/transactions/TransactionsController_getModuleTransactions
=> Feat: add transaction_hash query param for module txs

src/types/chains.ts
This adds the new `contractAddresses` object to the `ChainInfo` entity according to their inclusion in the [Safe Client Gateway](https://github.com/safe-global/safe-client-gateway/pull/1752) and [Safe Config. Service](https://github.com/safe-global/safe-config-service/pull/1175).
Reasoning: the Web currently relies on the `safe-deployments` package to initialise the SDK. This means, in order to run our infrastructure, addresses need be added to the aforementioned package. The values of `contractAddresses` map 1:1 with [the `ContractNetworksConfig`](https://docs.safe.global/sdk/protocol-kit/reference/safe#init)) of the `protocol-kit` making initialisation without presence in `safe-deployments` possible.
- Add new (`0x${string} | null`) fields to `ChainInfo['contractAddresses']`:
- …
=> Add `ChainInfo['contractAddresses']` property

src/utils.ts, tests/utils.test.ts
The delete transaction endpoint returns "OK" instead of a JSON. This seems to only happen in Cypress, so the behavior is not consistent across browsers (probably a bug in the CGW, @iamacook @hectorgomezv ?).
Anyway, this PR ignores non-JSON payloads and relies solely on the HTTP status code to return an error or success.
=> Fix: ignore failed json parse

src/index.ts, src/types/accounts.ts, src/types/api.ts
- Adds user account type definitions: `Account`, `AccountDataType`, `AcocuntDataSetting`, `CreateAccountDto`, `UpsertAccountDataSettingsDto`.
- Adds requests/responses specifications for the following user account endpoints:
- `POST /v1/accounts`
- `GET /v1/accounts/{address}`
- `DELETE /v1/accounts/{address}`
- `GET /v1/accounts/data-types`
- `GET /v1/accounts/{address}/data-settings`
- `PUT /v1/accounts/{address}/data-settings`
=> Feat: add CGW Accounts API specification

src/types/transactions.ts
CGW can return null in situations when fetching all children twap orders is undesirable/impossible. This was not reflected in the TWAP type and lead to crash if we try to convert the amount to a bigInt
=> fix: twap executed buy sell amount was incorrect

src/index.ts, src/types/api.ts
Changes `getDelegates` to use the v2 endpoint since the v1 endpoint is deprecated. The v2 endpoint expects the same payload and returns the same result: https://github.com/safe-global/safe-client-gateway/pull/1501
=> fix: Change getDelegates to use v2 endpoint

src/types/decoded-data.ts
Instead of having multiple statuses we are now opting for one stake status. Aligning with the changes on cgw in this PR: https://github.com/safe-global/safe-client-gateway/pull/1957
=> fix(Staking): stake statuses

package.json, src/index.ts, src/types/api.ts, src/types/chains.ts
Types for this endpoint: https://safe-client.staging.5afe.dev/api/#/chains/ChainsController_getIndexingStatus
=> Feat: chain indexing status

src/index.ts, src/types/api.ts, src/types/transactions.ts
As per https://github.com/safe-global/safe-wallet-web/issues/4331, the `confirmation-view` endpoint is being deprecated in favor of `preview`.
=> Feat: transaction preview endpoint

src/types/transactions.ts
CoW will be deprecated `executedSurplusFee`, favouring `executedFee` and `executedFeeToken` in its place.
The propagates the [associated changes on the Client Gateway](https://github.com/safe-global/safe-client-gateway/pull/2247) to the SDK.
- Mark `executedSurplusFee` as deprecated
- Remove `undefined` as a potential `executedSurplusFee` type
- Add `executedFee` and `executedFeeToken`
=> fix(Swaps): add `executedFee` and `executedFeeToken`

src/types/common.ts
It makes it compatible with the new RTK SDK.
=> Refactor: make TokeInfo type compatible with strings

src/utils.ts
The Client Gateway has [error inconsistencies](https://github.com/safe-global/safe-client-gateway/issues/1924) (which will be solved) meaning that status codes are either under the `status` or `statusCode` property.
This adds a fallback to use the `statusCode` property, meaning that error objects are recognised if that property is present over `code`.
- Detect error responses if `statusCode` is present.
- Fallback to `statusCode` value.
=> fix: fallback to `statusCode` in error message
