safe-global/safe-gateway-typescript-sdk

- .github/workflows/lint.yml
- .github/workflows/test.yml
Setting up a CI process is way too easy these days 😃
> Set up the CI

- .github/workflows/test.yml
- package.json
Combine the coverage & tests themselves.
> Simplify the test action

- package.json
- src/types/gateway.ts
The tx propose endpoint now returns the created tx's details. See https://github.com/gnosis/safe-client-gateway/pull/585
> Propose returns TransactionDetails

- .github/workflows/typedoc.yml
- README.md
* Generates a documentation site based on the TypeScript types.
* Publishes to GitHub pages.
> Publish typedoc

- .github/workflows/typedoc.yml
- .gitignore
- README.md
- e2e/safe-collectibles-list.test.ts
- package.json
- src/index.ts
- src/types/gateway.ts
The docs site: https://gnosis.github.io/safe-react-gateway-sdk/modules.html#getBalances
The TSDoc comments end up on that site as function descriptions. Once this PR is merged, the site will be updated.
> Add function annotations and a coverage report

- e2e/config.ts
- e2e/post-safe-gas-estimation.test.ts
- package.json
- src/endpoint.ts
- src/index.ts
- src/types/api.ts
- src/types/transactions.ts
- tests/endpoint.test.js
Create method for transaction estimation v2.
The GW version was moved to the `callEndpoint` path.
> Add post estimations v2

- src/types/transactions.ts
Add types to be used in `TransactionInfo` and update `TransactionListItem`  
* Add `TransactionInfo` -> `Cancelation` type
* Add `DateLabel` to `TransactionListItem` union type
> feat: add Cancellation type and update `TransactionListItem` union type

- package.json
- src/types/transactions.ts
- Adds missing `safeAddress` to `TransactionDetails` type as defined in the [gateway docs](https://safe.global/safe-client-gateway/docs/routes/transactions/models/details/struct.TransactionDetails.html)
> fix: Update TransactionDetails type

- src/endpoint.ts
- src/index.ts
- src/types/api.ts
- src/types/chains.ts
- src/types/safe-info.ts
- src/types/transactions.ts
- tsconfig.json
Ran into this while tightening our typescript config and type validation.
> fix: use import type where possible

- README.md
- package.json
- scripts/make-cgw-types.sh
- src/config.ts
- src/index.ts
Updates the default CGW host.
Also see https://github.com/safe-global/web-core/pull/981.
> Fix: update CGW URL

- README.md
> Fix: SDK links in the readme

- package.json
- src/types/chains.ts
Adds EIP1271 off-chain messages to feature enum
> Eip 1271 feature

- package.json
- src/types/safe-apps.ts
Implements changes from https://github.com/safe-global/safe-config-service/issues/739
> Add types for safe app social profiles and dev website

- LICENSE.md
> chore: Update license year

- LICENSE.md
Update the license time period
> chore: Update lincense period

- package.json
The linting command was not working correctly on Windows and this fixes it.
> chore: fix Windows linting

- package.json
Bump version for release v3.12.0
> chore: Bump version to v3.12.0

- package.json
- src/types/chains.ts
Adds `isTestnet` flag to chain config.
> feat: isTestnet flag for chains

- src/types/transactions.ts
We aligned on a new API structure for the swap feature and have to update the swap order types.
> fix: swap order type is no longer correct

- src/types/transactions.ts
export the new owner prop in the types
> feat: add swap owner prop

- .github/workflows/lint.yml
- src/types/transactions.ts
Add txHash to the Transaction type corresponding to the [changes on the client gateway](https://github.com/safe-global/safe-client-gateway/pull/1614). Intended for [grouping transactions executed in bulk](https://github.com/safe-global/safe-wallet-web/pull/3772).
> Feat: add `txHash` to `Transaction` type

- src/types/safe-apps.ts
This PR adds telegram to SafeAppSocialPlatforms
> Feat(Safe Apps): Add telegram to SafeAppSocialPlatforms

- tsconfig.json
This PR removes the deprecated options from the TypeScript config
> Chore: Remove deprecated options from the TypeScript config

- src/types/transactions.ts
Add a new property in MultisigExecutionDetails.
Needed for https://github.com/safe-global/safe-wallet-monorepo/issues/5680
> Feat: add proposedByDelegate
